# Generated by Django 5.1.6 on 2025-03-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('number_of_classes', models.IntegerField(verbose_name='Number_of_classes')),
                ('computed_area', models.FloatField(blank=True, editable=False, null=True, verbose_name='Area')),
            ],
        ),
    ]
