# Generated by Django 5.1.6 on 2025-03-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='computed_area',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Computed Area'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_classes',
            field=models.IntegerField(verbose_name='Number of Classes'),
        ),
    ]
